version: '3'

services:
  scm:
    image: "gfrosalino/backend-scm:alpha"
    ports: 
     - "3030:3030"
  user:
    image: "gfrosalino/backend-user:alpha"
    ports:
     - "3020:3020"
  frontend:
    image: "frontend:latest"
    ports:
     - "80:80"