apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-nodeport-yaml
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: kubernetes-dashboard
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443