kind: Service
apiVersion: v1
metadata:
  name: devopsbootcamp-questcode-frontend
spec:
  selector:
    app: devopsbootcamp-questcode-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080